### ISSUE TITLE
add apache rewrite rule to support the 63274 NAAN for ncpt

### ISSUE THREAD

**Issue by ashleygould** [CDLUC3/n2t-eggnog#1]
copied from n2t slack:

Hi N2T people, I need some help addressing a request from the team in Switzerland (INCIPIT) that is running an EZID clone and using N2T for resolution. As I understand it, they are onboarding their first user and they need the client's NAAN (63274) to be configured with N2T. They already obtained the NAAN through the normal process.John K was copied on the requests and he summarized what is needed as follows:

To support the 63274 NAAN, Maria's team will have to add an Apache Rewrite rule (to the $se/t/n2t/minder_builder scriptI think that roughly what's needed is one line added to the t/n2t/minder_builder file, something like,

```
RewriteRule ^/(ark:/?63274.*)\$ \\
  "_rslv_\${map_ncpt:\${esc:\$1%{ENV:THUMPER}}.resolve \${$hdrblob}}" [NC]

```
which will route incoming requests for their NAAN to their binder

**Comment by ashleygould** [comment]
Instructions for deploying this change (kinda rough)
```

# update n2t-eggnog (~/sv/cv2/build/eggnog)
cd $se
git pull
make
run 'make test'
less run.out
n2t test
n2t checkpoint
prior=$( < .rollback )
echo $prior
n2t rolltest

# roll back to git commit contained in .rollback (must run `n2t checkpoint` prior to n2t rolltest)
n2t rollback

```

**Comment by jkunze** [comment]
Between git pull and make, do "edit t/n2t/minder_builder" (find rewriterule with 68061, duplicate it, in the second rewriterule replace 68061 with 63274, write file and exit). 

Easiest way to test: add a test to t/egn_service_n2t.t - start by duplicating the existing test for the 68061 NAAN.

Do this in dev. After testing, push changes back to github.

Then go to stg, pull ... n2t rolltest.
Then go to prd, pull ... n2t rolltest.

**Comment by jkunze** [comment]
Prd installation doesn't have to wait until Sunday morning. Just pick a relatively calm time (eg, after 5pm), and run uptime until the numbers are lowish.

**Comment by ashleygould** [comment]
test added. fully merged.
